# -*- coding: utf-8 -*-
"""
/***************************************************************************
 getMedianFunctions
                                 A QGIS plugin
 This plugin shows a drop box with all the available functions for the chosen module
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-01
        copyright            : (C) 2020 by Kristaps Blumbergs
        email                : kristapsb52@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load getMedianFunctions class from file getMedianFunctions.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .median_functions import getMedianFunctions
    return getMedianFunctions(iface)
